stages:
  - lint
  - build
  - test
  - valgrind

.container:
  image: registry.cybbh.space/17d/bolc/docker/build:latest
  stage: build
  interruptible: true
  allow_failure: true
  tags:
    - docker
  timeout: 10m

.builder:
  extends:
    - .container
  stage: build
  before_script:
    - export PROJ=$CUR_PROJ
  script:
    - echo "Start clang-tidy Check"
    - echo "No output here is good"
    - echo "Ignore \"database\" erorrs for now"
    - find ${PROJ}/ -iname "*.c" -o -iname "*.h" | xargs -I {} clang-tidy {} "-checks=-*,clang-analyzer-*,-clang-analyzer-cplusplus*" -- -I${PROJ}/hdrs
    - echo "End clang-tidy Check"
    - cd $PROJ
    - ./build.sh

.tester:
  extends:
    - .builder
  stage: test
  allow_failure: false
  variables:
    GIT_STRATEGY: none
  before_script:
    - export PROJ=$CUR_PROJ
  script:
    - ls $PROJ
    - ls $PROJ/build/
    - python3 tests/${PROJ}Tests.py

.valgrind:
  extends: .builder
  variables:
    GIT_STRATEGY: none
  stage: valgrind
  before_script:
    - export PROJ=$CUR_PROJ
  script:
    - ""

# Sections for SimpleCalc
.SimpleCalc:
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /SimpleCalc/'
      when: always
  variables:
    CUR_PROJ: SimpleCalc

build:SimpleCalc:
  extends:
    - .builder
    - .SimpleCalc

test:SimpleCalc:
  extends:
    - .tester
    - .SimpleCalc
  needs:
    - build:SimpleCalc

valgrind:SimpleCalc:
  extends:
    - .valgrind
    - .SimpleCalc
  needs:
    - test:SimpleCalc
# End Sections for SimpleCalc


# Sections for FileCalc
.FileCalc:
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /FileCalc/'
      when: always
  variables:
    CUR_PROJ: FileCalc

build:FileCalc:
  extends:
    - .builder
    - .FileCalc

test:FileCalc:
  extends:
    - .tester
    - .FileCalc
  needs:
    - build:FileCalc
# End Sections for FileCalc


# Sections for FileChoiceCalc
.FileChoiceCalc:
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /FileChoiceCalc/'
      when: always
  variables:
    CUR_PROJ: FileChoiceCalc

build:FileChoiceCalc:
  extends:
    - .builder
    - .FileChoiceCalc

test:FileChoiceCalc:
  extends:
    - .tester
    - .FileChoiceCalc
  needs:
    - build:FileChoiceCalc
# End Sections for FileChoiceCalc
