stages:
  - lint
  - build
  - test

.container:
  image: registry.cybbh.space/17d/bolc/docker/build:latest
  stage: build
  interruptible: true
  allow_failure: false
  tags:
    - docker
  timeout: 10m

.linter: &lint
  extends:
    - .container
  stage: lint
  script:
    - apt update
    - apt-get install -y clang-format
    - 'find ./$CUR_PROJ -type f -name "*.c" | xargs clang-format --dry-run -Werror --style=file'
    - 'find ./$CUR_PROJ -type f -name "*.h" | xargs clang-format --dry-run -Werror --style=file'
  
.builder: &build
  extends:
    - .container
  stage: build
  script:
    - bash build.sh

.tester: &test
  extends:
    - .container
  stage: test
  script:
    - mkdir -p build
    - cd build
    - cmake -DDEBUG=1 ..
    - make -j$(nproc)
    - make test "ARGS= -R $CUR_TEST" 

JQRCalc-Build:
  needs: [ "Common-Lint", "SimpleCalc-Lint", "FileCalc-Lint", "ThreadCalc-Lint" ]
  <<: *build

Common-Lint:
  variables:
    CUR_PROJ: 0_Common
  <<: *lint

SimpleCalc-Lint:
  variables:
    CUR_PROJ: 1_SimpleCalc
    CUR_TEST: TestSimpleCalc
  <<: *lint

FileCalc-Lint:
  variables:
    CUR_PROJ: 2_FileCalc
    CUR_TEST: TestFileCalc
  <<: *lint

ThreadCalc-Lint:
  variables:
    CUR_PROJ: 4_ThreadCalc
    CUR_TEST: TestThreadCalc
  <<: *lint

SimpleCalc-Test:
  needs: [ "JQRCalc-Build" ]
  variables:
    CUR_PROJ: 1_SimpleCalc
    CUR_TEST: TestSimpleCalc
  <<: *test

FileCalc-Test:
  needs: [ "JQRCalc-Build" ]
  variables:
    CUR_PROJ: 2_FileCalc
    CUR_TEST: TestFileCalc
  <<: *test

ThreadCalc-Test:
  needs: [ "JQRCalc-Build" ]
  variables:
    CUR_PROJ: 4_ThreadCalc
    CUR_TEST: TestThreadCalc
  <<: *test
